[hook]
workers_num = 1
work_root = "/home/ccc/rust_xs_test_workload"
sleep_time = 120

[emu]
thread_num = 8
max_instr = 1000000
noop_home = "/home/ccc/XiangShan"
nemu_home = "/home/ccc/NEMU"
am_home = "/home/ccc/nexus-am"
img_list = "/bigdata/zyy/checkpoints_profiles/betapoint_profile_06"
